;PROGRAM DRV2.ASM
;LS-100 DRIVER PROGRAM 
;BY RVA 
;TO BE RELOCATED ABOVE CP/M
;BY THE RELOCATOR PROGRAM (LS100)
;
;LAST CHANGE
;11/21/83
;
;COPYRIGHT 1983
;DIGITAL RESEARCH COMPUTERS
;ALL RIGHTS RESERVED
;
;THE FLOWING EQUATES MUST MATCH THE VALUES
;IN THE LS100 FILE.
;
BIOS	EQU	0C300H		;BIOS ADDRESS
BDOS	EQU	0B506H		;BDOS ADDRESS
DRV2	EQU	0D800H		;LOAD ADDRESS OF DRIVER
;
;
CONOUT	EQU	BIOS+12		;BIOS CONSOLE OUTPUT
DRVID	EQU	04		;ACTIVE DRIVE # (E)
DRVLD	EQU	42H		;DRIVER ID BYTE
;
;LS-100 PORT ADDRESS ASSIGMENT
;
PBASE	EQU	000H		;BASE PORT ADDRESS
REG0	EQU	PBASE		;DATA TRANSFER PORT
REG1	EQU	PBASE+1		;MSB ADDRESS LATCH
REG2	EQU	PBASE+2		;LSB ADDRESS LATCH
REG3	EQU	PBASE+3		;BYTE LOCATION ADDRESS COUNTERS
NBYTES	EQU	128		;BYTES/SECTOR
;
;START OF DRIVER
;
	ORG	DRV2		;START OF DRIVER
	DB	DRVLD		;DRIVER ID BYTE
	DB	0
	DW	0,0		;6 BYTE OFFSET
BDOS1:	JMP	BDOS		;LINK TO BDOS ENTRY
;
;DRIVER BIOS JUMP TABLE
;
WBOOT1:	JMP	WBOOT		;WARM BOOT
HOME1:	JMP	HOME		;HOME
SLDSK1:	JMP	SLDSK		;SELECT DISK
STRK1:	JMP	STRK		;SET TRACK
SSEC1:	JMP	SSEC		;SET SECTOR
SDMA1:	JMP	SDMA		;SET DMA ADDRESS
RDE1:	JMP	RDE		;READ SECTOR
WRE1:	JMP	WRE		;WRITE SECTOR
LSTS1:	JMP	LSTS2		;LIST STATUS
SCTRL1: JMP	SCTRL		;SECTOR TRANSLATOR
;
;RELOCATED CP/M BIOS JUMP TABLE
;
WBOOT2:	DS	3		;WARM BOOT
HOME2:	DS	3		;HOME
SLDSK2:	DS	3		;SELECT DISK
STRK2:	DS	3		;SET TRACK
SSEC2:	DS	3		;SET SECTOR
SDMA2:	DS	3		;SET DMA ADDRESS
RDE2:	DS	3		;READ SECTOR
WRE2:	DS	3		;WRITE SECTOR
LSTS2:	DS	3		;LIST STATUS
SCTRL2: DS	3		;SECTOR TRANSLATOR
;
;
;
DPE0:	DW	XLT0,0000H	;TRANSLATE TABLE
	DW	0000H,0000H	;SCRATCH AREA
	DW	DIRBUF,DPB0	;DIR.BUF./PARM. BLOCK
	DW	CSV0,ALV0	;CHECK ALLOC. VECTORS
;
;THE FOLLOWING PARAMETERS ARE FOR 1 MEMORY BOARD
;
DPB0:	EQU	$		;DISK PARM. BLOCK
	DW	16		;SECTORS/TRACK
	DB	4		;BLOCK SHIFT
	DB	15		;BLOCK MASK
	DB	1		;EXTNT MASK
	DW	253		;SIZE-1
	DW	127		;MAX. DIR. ENTRYS
	DB	192		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
XLT0:	EQU	0		;NOT REQUIRED
;
;DRIVER ROUTINES
;
WBOOT:	JMP	WBOOT2		;READ IN CCP & BDOS

;
;HOME ROUTINE
;
HOME:	CALL	CHK		;CHECK FOR LS-100
	JNZ	HOME2		;IF NOT JUMP TO BIOS
	XRA	A		;CLEAR A
	STA	TRK		;SET TO TRACK 0
	RET
;
;SELECT DISK ROUTINE
;
SLDSK:	MOV	A,C		;GET DRIVE #
	STA	UNIT		;SAVE IT
	MVI	A,DRVID		;GET ACTIVE DRIVE #
	CMP	C		;CHECK FOR LS-100
	JNZ	SLDSK2		;IF NOT JUMP TO BIOS
	LXI	H,DPE0		;HL=DISK PARM. BLOCK
	RET
;
;SET TRACK ROUTINE
;
STRK:	CALL	CHK		;CHECK FOR LS-100
	JNZ	STRK2		;IF NOT JUMP TO BIOS
	MOV	A,C		;GET TRACK #
	STA	TRK		;STORE IT
	RET
;
;SET SECTOR ROUTINE
;
SSEC:	CALL	CHK		;CHECK FOR LS-100
	JNZ	SSEC2		;IF NOT JUMP TO BIOS
	MOV	A,C		;GET SECTOR #
	STA	SEC		;STORE IT
	RET
;
;SET UP DMA ADDRESS
;
SDMA:	MOV	H,B		;H=B
	MOV	L,C		;L=C
	SHLD	TADDR		;STORE IT
	JMP	SDMA2		;PASS PARM. TO BIOS
;
;LS-100 SECTOR TRANSLATE ROUTINE
;
SCTRL:	CALL	CHK		;CHECK FOR LS-100
	JNZ	SCTRL2		;IF NOT JUMP TO BIOS
	MOV	H,B		;NO TRANLASTION REQUIRED
	MOV	L,C		;SET HL=BC
	RET
;
;LS-100 SECTOR READ ROUTINE
;
RDE:	CALL	CHK		;CHECK FOR LS-100
	JNZ	RDE2		;IF NOT JUMP TO BIOS
	CALL	SETUP		;SET UP LS-100 REGS.
RDLP:	IN	REG0		;GET DATA FROM LS-100
	MOV	M,A		;STORE @ HL
	ADD	E		;COMPUTE CHECK SUM
	MOV	E,A		;ACCUMULATE CHECK SUM IN E
	INX	H		;BUMP POINTER
	DCR	B		;DECREMENT BYTE COUNT
	JNZ	RDLP		;LOOP UNTIL ZERO	
	CALL	CALC		;SET ADDRESS OF CHECK SUM BYTE
	IN	REG0		;GET CHECK SUM BYTE
	SUB	E		;CHECK FOR ERROR 
	RZ			;RETURN IF NO ERROR 
;
;PROCESS CHECK SUM ERROR
;
	LDA	TRK		;GET CURRENT TRACK #
	CALL	CNVHX		;CONVERT TO HEX ASCII
	SHLD	BDTRK		;PUT IN MESSAGE
	LDA	SEC		;GET CURRENT SECTOR #
	CALL	CNVHX		;CONVERT TO HEX ASCII
	SHLD	BDSCTR		;PUT IN MESSAGE
;
;FIND WHICH LS-100 BOARD THE ERROR OCCURED ON
;
	MVI	B,'1'		;START WITH BOARD #1
	LDA	SEC		;GET CURRENT SECTOR #
FIND:	SUI	8		;SUB. OFFSET/BOARD
	JC	FOUND		;CHECK FOR OVERFLOW
	INR	B		;BUMP BOARD COUNTER
	JMP	FIND		;KEEP LOOKING
FOUND:	MOV	A,B		;GET BOARD #
	STA	BDBRD		;PUT IN MESSAGE
;
;PRINT ERROR MESSAGE ON CONSOLE
;
	LXI	H,MESG1		;HL @ ERROR MESSAGE
SMESG:	MOV	A,M		;GET DATA
	ORA	A		;CHECK FOR END OF MESSAGE
	JZ	EXIT		;EXIT IF SO
	MOV	C,A		;SETUP FOR BIOS CALL
	PUSH	H		;SAVE POINTER
	CALL	CONOUT		;OUTPUT BYTE
	POP	H		;RESTORE POINTER
	INX	H		;BUMP POINTER
	JMP	SMESG		;LOOP UNTIL END OF MESSAGE
;
;SET DEFAULT DRIVE TO A AND ABORT
;
EXIT:	XRA	A		;CLEAR A
	MOV	C,A		;SET TO DRIVE A
	STA	4		;SET TO DRIVE A
	JMP 	0		;RETURN TO CP/M
;
;CONVERT HEX BYTE IN A. RETURN TWO HEX ASCII CHARS. IN HL
;
CNVHX:	PUSH	PSW
	RRC
	RRC
	RRC
	RRC
	CALL	HASCI
	MOV	L,A
	POP	PSW
	CALL	HASCI
	MOV	H,A
	RET
HASCI:	ANI	0FH
	ADI	90H
	DAA
	ACI	40H
	DAA
	RET			
;
;LS-100 SECTOR WRITE ROUTINE
; 
WRE:	CALL	CHK		;CHECK FOR LS-100
	JNZ	WRE2		;IF NOT JUMP TO BIOS
	CALL	SETUP		;SET UP LS-100 REGS.
WRLP:	MOV	A,M		;GET DATA FROM MEMY. @ HL
	OUT	REG0		;STORE DATA
	ADD	E		;COMPUTE CHECK SUM
	MOV	E,A		;ACCUMULATE CHECK SUM IN E
	INX	H		;BUMP POINTER
	DCR	B		;DECREMENT BYTE COUNT
	JNZ	WRLP		;LOOP UNTIL ZERO
	CALL	CALC		;SET ADDRESS OF CHECK SUM BYTE
	MOV	A,E		;GET CHECK SUM BYTE
	OUT	REG0		;STORE CHECK SUM BYTE
	XRA	A		;NORMAL RETURN
	RET
;
;SETUP LS-100 REGS. BASED ON CURRENT TRACK & SECTOR
;
SETUP:	LDA	TRK		;GET CURRENT TRACK #
	OUT	REG2		;SET LSB ADDRESS LATCH
	LDA	SEC		;GET CURRENT SECTOR #
	OUT 	REG1		;SET MSB ADDRESS LATCH
	LHLD	TADDR		;HL=DMA POINTER
	MVI	B,NBYTES	;B=BYTES/SECTOR
	MVI	E,0		;CLEAR CHECK SUM BYTE
	RET
;
;COMPUTE ADDRESS FOR CHECK SUM BYTE & SET UP LS-100 REGS.
;
CALC:	LXI	H,TRK		;HL @ TRACK #
	XRA	A		;CLEAR A/CARRY FLAG
	OUT	REG2		;SET TO TRACK 0
	MOV	A,M		;GET CURRENT TRACK
	RLC			;MOD 128
	JNC	SKP1		;JUMP IF <128
	MVI	A,1		;SET TO TRACK 1
	OUT	REG2		;UPDATE LSB ADDRESS LATCH
SKP1:	MOV	A,M		;RESTORE TRACK #
	OUT	REG3		;SET BYTE LOCATION ADDRESS COUNTERS
	RET
;
;CHECK THE CURRENT DRIVE BYTE FOR LS-100
;
CHK:	LDA	UNIT		;GET DRIVE #
	CPI	DRVID		;Z=0 DRIVE ACTIVE/Z=1 DRIVE NOT ACTIVE
	RET

;
;MESSAGE AREA
;
MESG1:	DW	0D0AH
	DB	'Checksum error occured on LS-100 board '
BDBRD:	DB	0
	DW	0D0AH
	DB	'at track '
BDTRK:	DW	0
	DB	'H'
	DB	' sector '
BDSCTR: DW	0
	DB	'H.'
	DW	0D0AH
	DB	0
;
;
;LOCAL STORAGE MUST BE IN RAM
;
UNIT:	DS	1		;CURRENT DRIVE
TRK:	DS	1		;CURRENT TRACK
SEC:	DS	1		;CURRENT SECTOR
TADDR:	DS	2		;TRANSFER ADDRESS
DIRBUF:	DS	128		;DIRECTORY ACCESS BUFFER
ALV0:	DS	64		;ALLOCATION VECTOR
CSV0:	DB	0		;CHECK SUM VECTOR
	END
