;PROGRAM FIND.ASM
;11/27/1983
;THIS PROGRAM WILL PRINT OUT 
;THE CURRENT BIOS & BDOS VALUES
;WHICH ARE LOCATED AT MEMORY
;LOCATIONS 2 AND 3 AND
;LOCATIONS 6 AND 7 RESPECTIVELY.
;
;
BDOS	EQU	5		;BDOS ENTRY POINT
PMSG	EQU	9		;PRINT STRING FUNCTION
;
;
	ORG	100H		;TPA
	LXI	SP,STACK	;INIT. PROGRAM STACK
	LDA	1		;GET LSB OF BIOS WARM BOOT
	SUI	03H		;ADJUST TO POINT TO COLD BOOT
	CALL	CNVHX		;CONVERT TO ASCII
	SHLD	MSG1B		;STORE RESULTS IN MESSAGE
	LDA	2		;GET MSB BIOS ADDRESS
	CALL	CNVHX		;CONVERT TO ASCII
	SHLD	MSG1A		;STORE RESULTS
	LDA	6		;GET LSB ADDRESS OF BDOS
	CALL	CNVHX		;CONVERT TO ASCII
	SHLD	MSG2B		;STORE RESULTS
	LDA	7		;GET MSB BDOS ADDRESS
	CALL	CNVHX		;CONVERT TO ASCII
	SHLD	MSG2A		;STORE RESULTS
	LXI	D,MSG		;SEND MESSAGE @ DE TO
	MVI	C,PMSG		;CONSOLE
	CALL	BDOS
	JMP	0		;DONE
;
;ENTER WITH A HEX BYTE IN ACCU.
;EXIT WITH 2 ASCII CHARS. IN HL
;
CNVHX:	PUSH	PSW
	RRC
	RRC
	RRC
	RRC
	CALL	HASCI
	MOV	L,A
	POP	PSW
	CALL	HASCI
	MOV	H,A
	RET
HASCI:	ANI	0FH
	ADI	90H
	DAA
	ACI	40H
	DAA
	RET
;
;MESSAGE AREA
;
MSG:	DB	'                       BIOS - BDOS LOCATOR'
	DW	0D0AH
	DW	0D0AH
	DB	'      BIOS VALUE = '
MSG1A:	DW	0
MSG1B:	DW	0
	DB	'H'
	DW	0D0AH
	DB	'      BDOS VALUE = '
MSG2A:	DW	0
MSG2B:	DW	0
	DB	'H'
	DW	0D0AH
	DB	'$'
;
;PROGRAM STACK AREA
;
	DS	10
STACK:	EQU	$
	END
