;PROGRAM LS100.ASM
;LS-100 DRIVER RELOCATOR PROGRAM 
;BY RVA
;LAST CHANGE
;11/21/83
;
;COPYRIGHT 1983
;DIGITAL RESEARCH COMPUTERS
;ALL RIGHTS RESERVED
;
;THIS PROGRAM WILL RELOCATE THE LS-100 DRIVER PROGRAM (DRV2)
;FROM 1000H TO A USER DEFINED DESTINATION ADDRESS.
;THIS WILL ALLOW YOU TO HAVE A MAXMIMUN CP/M SYSTEM SIZE
;AS THE DRIVER PROGRAM IS OUT OF THE TPA AREA. THEREFORE IT IS NO
;LONGER NESSARY TO PROTECT THE DRIVER FROM BEING OVER WRITTEN.
;NOTE HOWEVER THAT IF THE WARM BOOT ROUTINE OVER WRITES THE BIOS
;JUMP TABLE AS IS DONE ON A COLD BOOT THEN THE DRIVER PROGRAM WILL
;HAVE TO BE RE-INSTALLED ON EACH WARM BOOT. THIS PROBLEM IS RARE BUT
;IT MAY EXIST. THE ONLY CURE FOR THIS PROBLEM IS TO MODIFY THE 
;BIOS WARM BOOT ROUTINE TO READ IN ONLY THE CCP AND BDOS AS DESCRIBED 
;IN THE SYSTEM ALTERATION GUIDE FROM DIGITAL RESEARCH. 
;NOTE THAT THE DRIVER PROGRAM AS SUPPLIED
;REQUIRES 618 BYTES OF RAM STORAGE.
;
;
;
;THE PROGARM BDOS & BIOS VALUES MUST MATCH
;YOU'RE CURRENT CP/M BDOS & BIOS VALUES.
;NOTE THAT SOME CP/M SYSTEMS HAVE AN OFFSET FROM
;THE STANDARD CP/M VALUES AS PUBLISHED IN THE CP/M 2.2
;DOCUMENTATION. 
;IF YOU DO NOT KNOW THE BDOS & BIOS VALUES FOR YOU'RE SYSTEM
;YOU CAN FIND THE VALUES WITH THE FIND.COM PROGRAM SUPPLIED 
;ON THE DISTRIBUTION DISK.
;ENTER THE BDOS & BIOS VALUES INTO
;THE SOURCE CODE BELOW.
;
BDOS	EQU	0B506H		;BDOS ADDRESS
BIOS	EQU	0C300H		;BIOS ADDRESS
;
;SET DRV2 EQUAL TO THE DESTINATION ADDRESS OF THE DRIVER.
;BE SURE TO ALLOW ENOUGH RAM FOR THE DRIVER TO FIT.
;
DRV2	EQU	0D800H		;LOAD ADDRESS OF DRIVER 
DRVSZ	EQU	618		;SIZE OF DRV2 PROGRAM
;
DRVID	EQU	04		;ACTIVE DRIVE # (E)
DRVLD	EQU	42H		;DRIVER LOADED FLAG
TABSZ	EQU	0FH		;SIZE OF DRIVE TABLE ENTRY
DPB	EQU	DRV2+55H	;ADDRESS OF DISK PARM. BLOCK
;
;
;LS-100 BOARD EQUATES
;
PBASE	EQU	000H		;BASE PORT ADDRESSŠREG0	EQU	PBASE		;DATA TRANSFER PORT
REG1	EQU	PBASE+1		;MSB ADDRESS LATCH
REG2	EQU	PBASE+2		;LSB ADDRESS LATCH
REG3	EQU	PBASE+3		;BYTE LOCATION COUNTERS
;
;		TO CREATE LS100.COM
;
;	ASM LS100		;MAKE HEX FILE
;	ASM DRV2		;MAKE HEX FILE
;	DDT LS100.HEX		;READ IN RELOCATOR
;	H0,(ADDRESS OF DRV2)	;GET DRIVER OFFSET FROM 0H
;				;ADD 1000H TO DIFF. TO GET FINAL OFFSET
;	IDRV2.HEX		;SET UP TO READ IN LS-100 DRIVER
;	R(FINAL OFFSET)		;READ DRVIER INTO MEMORY AT 1000H
;	G0			;EXIT DDT
;	SAVE 18 LS100.COM 	;SAVE RELOCATOR AND DRIVER
;	
;
	ORG	0100H		;MAKE COM FILE
	LXI	SP,STACK	;SET UP SYSTEM STACK
;
;CHECK FOR # OF BOARDS IN SYSTEM
;
	CALL	FIND		;FIND # OF BOARDS
	MOV	A,C		;PUT IN A
	ORA	A		;SET FLAGS
	JZ	ERR1		;CAN'T BE 0
	STA	NUMBD		;SAVE COUNT
	ADI	30H		;MAKE ASCII
	STA	BDS		;PUT IN MESSAGE
;
;CHECK CP/M VER. #
;
MAIN:	MVI	C,0CH		;VERSION FUNC.
	CALL	5
	CPI	20H		;CHECK FOR 2.0 OR BETTER
	JNC	VEROK
	LXI	D,MESG4		;WRONG VERSION
	CALL	SMESG
	JMP	0		;ABORT
;
;MOVE DRIVER 
;
VEROK:	LXI	D,MESG1		;SIGN ON
	CALL	SMESG
MOV1:	LXI	H,1000H		;HL=SOURCE OF DRIVER
	LXI	D,DRV2		;DE=DEST. OF DRIVER
	LXI	B,DRVSZ		;BC=LENGTH OF DRIVER
	CALL	MOVIT		;MOVE INTO POSTION
;
;COPY BIOS JUMP TABLE TO RELOCATED BIOS JUMP TABLE
;
MOV2A:	LXI	H,BIOS+3	;HL=BIOS JUMP TABLE
	LXI	D,DRV2+27H	;DE=RELOCATED BIOS JUMP TABLE
	LXI	B,3		;# OF BYTESŠ	CALL	MOVIT		;COPY WARM BOOT
	LXI	D,12H		;SKIP PAST UNUSED ENTRIES
	DAD	D		;ADJUST HL
	LXI	D,DRV2+2AH	;DE=DEST.
	LXI	B,1BH		;# OF BYTES
	CALL	MOVIT		;COPY HOME-SECTOR TRANSLATE
;
;COPY DRIVER JUMP TABLE INTO BIOS JUMP TABLE
;
MOV2B:	LXI	H,DRV2+9	;HL=DRIVER BIOS
	LXI	D,BIOS+3	;DE=DEST.
	LXI	B,3		;# OF BYTES
	CALL	MOVIT		;COPY WARM BOOT
	LXI	D,BIOS+18H	;SKIP PAST UNUSED ENTRIES
	LXI	B,1BH		;# OF BYTES
	CALL	MOVIT		;COPY HOME-SECTOR TRANSLATE
;
; FILL IN DISK PRAMTER BLOCK BASED ON # OF BOARDS IN SYSTEM
;
	LXI	D,MESG5
	CALL	SMESG
	LDA	NUMBD
	LXI	H,DRVTAB	;HL@ DRIVE TABLE
	DCR	A		;MAKE RELATIVE 0
	JZ	CALC2		;SKIP IF ONLY 1 BOARD
	LXI	D,TABSZ		;DE=SIZE OF TABLE
CALC1:	DAD	D		;INDEX INTO TABLE
	DCR	A		;DECREMENT A
	JNZ	CALC1		;UNTIL A=0
CALC2:	LXI	D,DPB		;HL=SOURCE/DE=DEST.
	LXI	B,TABSZ		;BC=LENGTH
	CALL	MOVIT		;MOVE INTO POSTION
;
;END OF MAIN PROGRAM
;
	LXI	D,MESG2		;DONE
	CALL	SMESG
	JMP	0	
;
;FIND # OF BOARDS IN SYSTEM
;
FIND:	XRA	A		;CLEAR A
	MOV	B,A		;"   " B
	MOV	C,A		;"   " C
	OUT	REG2		;CLEAR LSB LATCH
FIND1:	OUT	REG1		;SET MSB LATCH
	CALL	TEST		;CHECK FOR A BOARD
	RNZ			;RETURN WHEN NO BOARD FOUND
	MOV	A,B		;B=SECTORS/BOARD
	ADI	08		;ADD BOARD OFFSET
	CPI	40H		;CHECK FOR OVERFLOW
	JZ	ERR2		;REPORT ERROR
	MOV	B,A		;RESULTS IN B
	INR	C		;INCREMENT BOARD COUNTER
	JMP	FIND1		;KEEP LOOKINGŠ;
;NON-DESTRUCTIVE BYTE TEST
;
TEST:	CALL	RESET		;CLEAR BYTE LOCATION ADDRESS
	IN	REG0		;READ DATA
	MOV	D,A		;SAVE IN D
	CALL	RESET		;CLEAR BYTE LOCATION ADDRESS
	MVI	A,55H		;GET TEST BYTE
	OUT	REG0		;WRITE IT
	CALL	RESET		;CLEAR BYTE LOCATION ADDRESS
	IN	REG0		;READ DATA BACK
	CPI	55H		;CHECK FOR TEST BYTE
	CALL	RESET		;CLEAR BYTE LOCATION ADDRESS
	MOV	A,D		;GET ORGINAL DATA
	OUT	REG0		;RESTORE DATA
	RET
;
;RESET BYTE ADDRESS COUNTERS
;
RESET:	MVI	A,0		;CLEAR A/SAVE FLAGS
	OUT	REG3		;SET BYTE LOCATION ADDRESS
	RET
;
;BLOCK MOVE ROUTINE
;HL=SOURCE/DE=DEST./BC=COUNT
;
MOVIT:	MOV	A,M		;GET DATA
	STAX	D		;STORE IT
	INX	H		;BUMP SOURCE POINTER
	INX	D		;BUMP DEST. POINTER
	DCX	B		;DECREMENT COUNTER
	MOV	A,B		;A=B
	ORA	C		;CHECK FOR BC=0
	JNZ	MOVIT		;LOOP UNTIL BC=0
	RET
;
;NO LS-100 BOARDS FOUND
;
ERR1:	LXI	D,MESG6
	CALL	SMESG
	JMP	0
;
;TO MANY LS-100 BOARDS FOUND
;
ERR2:	LXI	D,MESG7
	CALL	SMESG
	JMP	0
;
;SEND MESSAGE @DE TO CON.
;
SMESG:	MVI	C,09H
	JMP	5
;
;DISK DRIVE PRAMETER TABLES
;ŠDRVTAB:	EQU	$
;
DPB0:	DW	8		;SECTORS/TRACK
	DB	4		;BLOCK SHIFT
	DB	15		;BLOCK MASK
	DB	1		;EXTNT. MASK
	DW	126		;DISK SIZE-1
	DW	127		;MAX. DIRECTORY ENTRIES
	DB	192		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
;
DPB1:	DW	16		;SECTORS/TRACK
	DB	4		;BLOCK SHIFT
	DB	15		;BLOCK MASK
	DB	1		;EXTNT. MASK
	DW	253		;DISK SIZE-1
	DW	127		;MAX. DIRECTORY ENTRIES
	DB	192		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
;
DPB2:	DW	24		;SECTORS/TRACK
	DB	5		;BLOCK SHIFT
	DB	31		;BLOCK MASK
	DB	3		;EXTNT. MASK
	DW	189		;DISK SIZE-1
	DW	255		;MAX. DIRECTORY ENTRIES
	DB	192		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
;
DPB3:	DW	32		;SECTORS/TRACK
	DB	5		;BLOCK SHIFT
	DB	31		;BLOCK MASK
	DB	3		;EXTNT. MASK
	DW	253		;DISK SIZE-1
	DW	255		;MAX. DIRECTORY ENTRIES
	DB	192		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
;
DPB4:	DW	40		;SECTORS/TRACK
	DB	6		;BLOCK SHIFT
	DB	63		;BLOCK MASK
	DB	7		;EXTNT. MASK
	DW	157		;DISK SIZE-1
	DW	511		;MAX. DIRECTORY ENTRIES
	DB	192		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZEŠ	DW	2		;OFFSET
;
DPB5:	DW	48		;SECTORS/TRACK
	DB	6		;BLOCK SHIFT
	DB	63		;BLOCK MASK
	DB	7		;EXTNT. MASK
	DW	189		;DISK SIZE-1
	DW	511		;MAX. DIRECTORY ENTRIES
	DB	192		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
;
DPB6:	DW	56		;SECTORS/TRACK
	DB	6		;BLOCK SHIFT
	DB	63		;BLOCK MASK
	DB	7		;EXTNT. MASK
	DW	221		;DISK SIZE-1
	DW	1023		;MAX. DIRECTORY ENTRIES
	DB	240		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
;
DPB7:	DW	64		;SECTORS/TRACK
	DB	6		;BLOCK SHIFT
	DB	63		;BLOCK MASK
	DB	7		;EXTNT. MASK
	DW	253		;DISK SIZE-1
	DW	1023		;MAX. DIRECTORY ENTRIES
	DB	240		;ALLOC0
	DB	0		;ALLOC1
	DW	0		;CHECK SIZE
	DW	2		;OFFSET
;
;
;
;MESSAGE AREA
;
MESG1:	DW	0D0AH
	DB	'                 LS-100  Auto  Install  Program.'
	DW	0D0AH
	DW	0D0AH
;	DB	'                   DIGITAL REASEARCH COMPUTERS'
;	DW	0D0AH
;	DB	'                       ALL RIGHTS RESERVED' 
;	DW	0D0AH
;	DB	'                          COPYRIGHT 1983'
;	DW	0D0AH
;	DB	'                             VER. 2.0'
;	DW	0D0AH
;	DW	0D0AH
	DB	'$'
MESG2:	DW	0D0AH
	DW	0D0AHŠ	DB	'Drive '
	DB	DRVID+41H
	DB	' active'
	DW	0D0AH
	DB	'$' 
MESG4:	DB	'CP/M 2.0 or better required'
	DW	0D0AH
	DB	'$'
MESG5:	DW	0D0AH
	DB	'Driver installed for '
BDS:	DS	1
	DB	' LS-100 board'
	DW	0D0AH
	DB	'$'
MESG6:	DB	'No boards found'
	DW	0D0AH
	DB	'$'
MESG7:	DB	'Number of boards found exceed limit'
	DW	0D0AH
	DB	'$'
NUMBD:	DS	1		;NUMBER OF BOARDS FOUND	
	DS	20
STACK	EQU	$
	END
