; Modified from original code by RCL9, July 29 1984.
; Cleaned up message appearance.

;LS-100
;AUTO FORMAT PROGRAM 
;BY RVA
;COPYRIGHT 1983
;DIGITAL RESEARCH COMPUTERS
;ALL RIGHTS RESERVED
;
;THIS PROGRAM WILL FIND THE NUMBER OF
;LS-100 BOARDS IN THE SYSTEM THEN FORMAT THE
;CHECK SUM TRACKS WITH AN 80H, AND THE DATA 
;TRACKS WITH AN E5H 
;
PBASE	EQU	000H		;BASE PORT ADDRES
REG0	EQU	PBASE		;DATA TRANSFER PORT
REG1	EQU	PBASE+1		;MSB ADDRESS LATCH
REG2	EQU	PBASE+2		;LSB ADDRESS LATCH
REG3	EQU	PBASE+3		;BYTE LOCATION ADDRESS
NBYTES	EQU	128		;BYTES/SECTOR
BDOS	EQU	5		;BDOS
;
	ORG	0100H		;MAKE COM FILE
MAIN:	LXI	SP,STACK	;SET UP STACK	
	LXI	D,MESG1		;SIGN ON
	CALL	SMESG
	CALL	FIND		;FIND # OF BOARDS
	MOV	A,B		;B=SECTORS/TRACK
	ORA	A		;CANT BE 0
	JZ	ERR1		;PRINT WARNING
	STA	NSCTR		;SAVE SECTORS/TRACK
	MOV	A,C		;GET # OF BOARDS FOUND
	STA 	NUMBD		;PUT IN MESSAGE
	LXI	D,MESG7
	CALL	SMESG
	MVI	A,80H		;GET CHECK SUM BYTE
	STA	FBYTE		;SAVE IT
	MVI	A,1		;WRITE MODE
	STA	MODE		;SET MODE TO WRITE
	MVI	H,2		;H=TRACKS TO FORMAT
	MVI	D,0		;CLEAR TRACK COUNTER
	CALL	FMATE		;DO IT
	MVI	A,0E5H		;GET FORMAT BYTE
	STA	FBYTE		;SAVE IT
	MVI	H,254		;H=TRACKS LEFT TO FORMAT
	CALL	FMATE		;DO IT
	LXI	D,MESG6
	CALL	SMESG
	XRA	A		;SET TO READ MODE
	STA	MODE		;SET MODE BYTE
	MVI	A,80H		;GET COMPARE BYTE
	STA	FBYTE		;SAVE IT
	MVI	H,2		;# OF TRACKS TO VERIFY
	MVI	D,0		;CLEAR TRACK COUNTER
	CALL	FMATE		;VERIFY TRACKS
	MVI	A,0E5H		;GET COMPARE BYTE
	STA	FBYTE		;SAVE IT
	MVI	H,254		;# OF TRACKS TO VERIFY
	CALL	FMATE		;VERIFY TRACKS
	LXI	D,MESG2		;FORMAT COMPLEATE
	CALL	SMESG
	JMP	0		;DONE
;
FMATE:	XRA	A		;CLEAR A
	MOV	C,A		;C=CURRENT SECTOR #
	LDA	NSCTR		;GET SECTORS/TRACK
	MOV	B,A		;B=SECTOR COUNTER
	MOV	A,D		;D=CURRENT TRACK
	OUT	REG2		;SET LSB LATCH
FMATE1:	MOV	A,C		;GET CURRENT SECTOR #
	OUT	REG1		;SET MSB LATCH
	MVI	L,NBYTES/16	;L=BYTES/SECTOR
	LDA	MODE		;CHECK FOR READ OR WRITE
	ORA	A		;0=READ/1=WRITE
	JZ	RDE		;READ SECTOR
	CALL	WRTE		;WRITE SECTOR
FMATE2:	INR	C		;BUMP CURRENT SECTOR #
	DCR	B		;DECREMENT SECTOR COUNTER
	JNZ	FMATE1		;FILL SECTORS
	INR	D		;BUMP CURRENT TRACK COUNT
	DCR	H		;DECREMENT TRACK COUNTER
	JNZ	FMATE		;FILL TRACKS
	RET
;
RDE:	PUSH	B		;SAVE BC
	LDA	FBYTE		;GET COMPARE BYTE
	MOV	B,A		;IN B
RDLP	IN	REG0		;GET DATA
	CMP	B		;CHECK IT
	CNZ	RDERR		;PRINT ANY ERRORS
	IN	REG0
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	IN	REG0	
	CMP	B	
	CNZ	RDERR	
	DCR	L		;DECREMENT BYTE COUNTER
	JNZ	RDLP		;READ ALL BYTES
	POP	B		;RESTORE BC
	JMP	FMATE2		;READ REST OF DATA
;
WRTE:	LDA	FBYTE		;GET FILL BYTE
WRLP:	OUT	REG0		;WRITE DATA
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	OUT	REG0
	DCR	L		;DECREMENT BYTE COUNTER
	JNZ	WRLP		;FILL CURRENT SECTOR
	RET
;
FIND:	XRA	A		;CLEAR A
	MOV	B,A		;CLEAR B
	MVI	C,30H		;C=NUMBER OF BOARDS FOUND
	OUT	REG2		;SET LSB LATCH
FIND1:	OUT	REG1		;SET MSB LATCH
	CALL	TEST		;CHECK FOR A BOARD
	RNZ			;BOARDS FOUND
	MOV	A,B		;GET SECTORS/BOARD
	ADI	8		;ADD BOARD OFFSET 
	CPI	40H		;MAX. BOARDS ALLOWED
	JZ	ERR2		;PRINT WARNING & ABORT
	INR	C		;BUMP BOARD COUNT
	MOV	B,A		;SAVE OFFSET
	JMP	FIND1		;KEEP LOOKING
;
TEST:	CALL	RESET		;RESET BYTE LOCATION COUNTERS
	MVI	A,55H		;GET TEST BYTE
	OUT	REG0		;WRITE IT
	CALL	RESET		;RESET COUNTERS
	IN	REG0		;READ DATA
	CPI	55H		;CHECK IT
	RET		
;
RESET:	XRA	A		;CLEAR A
	OUT	REG3		;SET BYTE LOCATION TO 0
	RET
;			
ERR1:	LXI	D,MESG3		;CAN'T FIND ANY BOARDS
	CALL	SMESG
	JMP	0		;ABORT
;
ERR2:	LXI	D,MESG4		;BOARDS FOUND EXCEED LIMIT
	CALL	SMESG
	JMP	0		;ABORT
;
RDERR:	PUSH	H		;SAVE WORKING REGS.
	PUSH	D
	PUSH	B
	PUSH	PSW
	MOV	A,D		;GET CURRENT TRACK #
	CALL	CNVHX		;CONVERT TO ASCII IN HL
	SHLD	BDTRK		;PUT INTO MESSAGE
	MOV	A,C		;GET CURRENT SECTOR #
	CALL	CNVHX		;CONVERT TO ASCII
	SHLD	BDSCTR		;PUT IN MESSAGE
	MOV	A,B		;GET GOOD DATA BYTE
	CALL	CNVHX		;CONVERT
	SHLD	GBYT		;STORE IN MESSAGE
	POP	PSW		;GET BAD BYTE
	CALL	CNVHX		;CONVERT
	SHLD	BDBYT		;STORE IN MESSAGE
	LXI	D,MESG5		;PRINT ERROR MESSAGE
	CALL	SMESG
	MVI	C,01		;GET RESPONSE
	CALL	BDOS
	CPI	1BH		;CHECK FOR ABORT
	JZ	0
	POP	B		;CONTINUE
	POP	D
	POP	H		;RESTORE REGS.
	RET
;
CNVHX:	PUSH	PSW		;SAVE CONVERT BYTE
	RRC
	RRC
	RRC
	RRC			;MOVE INTO POSITION
	CALL	HASCI		;CONVERT NIBBLE
	MOV	L,A		;SAVE IN L
	POP	PSW		;RESTORE BYTE
	CALL	HASCI		;CONVERT NIBBLE
	MOV	H,A		;SAVE IN H
	RET
;
HASCI:	ANI	0FH		;MASK MSB NIBBLE
	ADI	90H		;A-F CAUSE CARRY
	DAA			;ADJUST
	ACI	40H		;ADD IN CARRY
	DAA			;ADJUST
	RET
;
SMESG:	MVI	C,09H		;PRINT MESSAGE FUNCTION
	JMP	BDOS		;LET CP/M DO THE WORK
;
MESG1:	DB	'                LS-100  Auto  Format  Program'
	DW	0D0AH
	DW	0D0AH
;	DB	'                 DIGITAL RESEARCH COMPUTERS'
;	DW	0D0AH
;	DB	'                     ALL RIGHTS RESERVED'
;	DW	0D0AH
;	DB	'                       COPYRIGHT 1983'
;	DW	0D0AH
;	DB	'                          VER. 1.0'
;	DW	0D0AH
;	DW	0D0AH
	DB	'$'
MESG2:	DB	'Done                               '
	DW	0D0AH
	DB	'$'
MESG3:	DB	'No LS-100 boards found.'
	DW	0D0AH
	DB	'$'
MESG4:	DB	'Boards found exceed limit.'
	DW	0D0AH
	DB	'Check for port addressing error.'
	DW	0D0AH
	DB	'$' 
MESG5:	DB	'Verify error at: Sector '
BDSCTR: DS	2
	DB	' , track '
BDTRK:	DS	2
	DB	'.'
	DW	0D0AH
	DB	'Good data '
GBYT:	DS	2
	DB	' ,bad data '
BDBYT:	DS	2
	db	'.'
	DW	0D0AH
	DB	'Enter ESC to ABORT, any other key to continue.'
	DW	0D0AH	
	DB	'$'
MESG6:	DB	'Verifying format.              '
	DW	0DH
	DB	'$'
MESG7:	DB	'Formating '
NUMBD:	DB	0
	DB	' LS-100 board.'
	DW	0DH
	DB	'$'
;
;PROGRAM STORAGE AREA
;THIS MUST BE IN RAM
;
NSCTR:	DS	1		;SECTORS/TRACK
FBYTE:	DS	1		;FILL BYTE
MODE:	DS	1		;MODE BYTE
	DS	20
STACK:	EQU	$
	END
